// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // எரரைச் சரி செய்ய வெர்ஷனை 8.9.1 ஆக மாற்றியுள்ளோம்
        classpath 'com.android.tools.build:gradle:8.13.2'
        // classpath 'com.google.gms:google-services:4.5.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build the gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}